version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DB_ID=${NOTION_DB_ID}
      - FRAMEIO_TOKEN=${FRAMEIO_TOKEN}
    restart: always
    networks:
      - csb-network

networks:
  csb-network:
    driver: bridge
